[package]
name = "storage-tank"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
medianheap = "0.1"
ordered-float = "1.0"
measurements = "0.10"
rppal = { version = "0.10.0", git = "https://github.com/golemparts/rppal", rev = "3932b8eb97e714d2715f3929555a3a0653ea565e" }
simple-signal = "1"
vessel = { path = "vessel" }
