[package]
name = "heating"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2021"
publish = false

[profile.release]
opt-level = 3
lto = true

[dependencies]
actix-rt = "2"
env_logger = "0.11"
lazy_static = "*"
log = "0.4"
vcontrol = { version = "*", features = ["webthing"] }
webthing = "0.15"
serde_json = "1"
tokio = "1"

[patch.crates-io]
vcontrol = { git = "https://github.com/reitermarkus/vcontrol-rs" }
# vcontrol = { path = "../../../Repos/vcontrol-rs" }
webthing = { git = "https://github.com/WebThingsIO/webthing-rust" }
