#!/bin/bash

set -e
set -o pipefail
set -o nounset

[ "${1:-}" = pi ] && shift

rust_version="$(rustc --version | cut -d ' ' -f 2)"

if [ -z "$CARGO_HOME" ]; then
  CARGO_HOME=~/.cargo
fi

docker run --rm \
  --volume "$(pwd)":/home/cross/project \
  --volume "$CARGO_HOME"/registry:/home/cross/.cargo/registry \
  ragnaroek/rust-raspberry:"$rust_version" \
  $@
