[package]
name = "heating"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"
publish = false

[profile.release]
opt-level = 3
lto = true

[dependencies]
actix-rt = "2.7"
env_logger = "0.9"
fc113 = { path = "fc113" }
hc-sr04 = { path = "hc-sr04" }
lazy_static = "*"
log = "0.4"
vessel = { path = "vessel" }
vcontrol = { version = "*", features = ["impl_webthing"] }
webthing = "0.15"
serde_json = "1.0"
tokio = "1.0.0"

[patch.crates-io]
phf = { git = "https://github.com/rust-phf/rust-phf" }
vcontrol = { git = "https://github.com/reitermarkus/vcontrol-rs" }
# vcontrol = { path = "../../../Repos/vcontrol-rs" }
