[package]
name = "heating"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
env_logger = "0.7"
fc113 = { path = "fc113" }
hc-sr04 = { path = "hc-sr04" }
lazy_static = "*"
log = "0.4"
lru_time_cache = "0.9"
measurements = "0.10"
medianheap = "0.2"
ordered-float = "1"
rocket = "0.4"
rocket_contrib = "0.4"
rppal = "0.11"
serde_json = "1"
simple-signal = "1"
vessel = { path = "vessel" }
vcontrol = { version = "0.3", git = "https://github.com/reitermarkus/vcontrol-rs", branch = "master" }
