#!/bin/bash

set -e
set -o pipefail
set -o nounset

ip="${1}"

TARGET='arm-unknown-linux-gnueabihf'

cross build --release --target "${TARGET}"

vcontrol_root="$(dirname "$(cargo metadata --format-version 1 | jq -r '.packages | map(select(.name == "vcontrol"))[0].manifest_path')")"
vcontrol_config="${vcontrol_root}/config/default.yml"
cp -f "${vcontrol_config}" "target/${TARGET}/release/config.yml"

rsync -avz --include heating --include config.yml --exclude '*' "target/${TARGET}/release/" pi@"${ip}:/tmp/heating/"

ssh pi@"${ip}" sudo timedatectl set-timezone Europe/Vienna
echo 'heizung' | ssh pi@"${ip}" sudo tee /etc/hostname

cat <<CONFIG | ssh pi@"${ip}" sudo tee /etc/systemd/system/heating.service
[Unit]
Description=heating

[Service]
Type=simple
Environment=OPTOLINK_DEVICE=/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A902YK66-if00-port0
Environment=ROCKET_PORT=80
Environment=ROCKET_SECRET_KEY="$(openssl rand -base64 32)"
ExecStart=/usr/local/bin/heating
Restart=always

[Install]
WantedBy=multi-user.target
CONFIG

ssh pi@"${ip}" sudo cp -f /tmp/heating/heating /usr/local/bin/heating
ssh pi@"${ip}" sudo mkdir -p /etc/heating
ssh pi@"${ip}" sudo cp -f /tmp/heating/config.yml /etc/heating/config.yml
ssh pi@"${ip}" sudo systemctl enable heating
ssh pi@"${ip}" sudo systemctl restart heating
