#!/bin/bash

set -e
set -o pipefail
set -o nounset

ip="${1}"

TARGET='arm-unknown-linux-gnueabihf'

cross build --release --target "${TARGET}"

rsync -avz --include heating --exclude '*' "target/${TARGET}/release/" pi@"${ip}:/tmp/heating/"

ssh pi@"${ip}" < setup_timezone.sh
ssh pi@"${ip}" < setup_hostname.sh

ssh pi@"${ip}" < setup_watchdog.sh

cat <<CONFIG | ssh pi@"${ip}" sudo tee /lib/udev/rules.d/99-optolink.rules
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", ATTRS{serial}=="A902YK66", SYMLINK+="optolink"
CONFIG

cat <<CONFIG | ssh pi@"${ip}" sudo tee /etc/systemd/system/heating.service
[Unit]
Description=heating
BindsTo=dev-optolink.device
After=dev-optolink.device
StartLimitAction=reboot
StartLimitIntervalSec=60
StartLimitBurst=10

[Service]
Type=simple
Environment=OPTOLINK_DEVICE=/dev/optolink
Environment=ROCKET_PORT=80
Environment=RUST_LOG=info
Environment=ROCKET_SECRET_KEY="$(openssl rand -base64 32)"
ExecStart=/usr/local/bin/heating
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
CONFIG

ssh pi@"${ip}" sudo mv -f /tmp/heating/heating /usr/local/bin/heating
ssh pi@"${ip}" sudo systemctl enable heating
ssh pi@"${ip}" sudo systemctl restart heating
