- name: Set up Raspberry Pi
  hosts: raspberry_pi
  become: yes
  tasks:
    - name: Install requirements
      local_action: command ansible-galaxy install -r requirements.yml
      become: no
      tags:
        - setup
    - name: Setup
      import_role:
        name: reitermarkus.raspberry_pi.setup
      vars:
        timezone: Europe/Vienna
        watchdog: on
    - name: Install ser2net
      apt:
        name: ser2net
    - name: Configure ser2net
      copy:
        content: |
          %YAML 1.1
          ---
          connection: &con01
            accepter: tcp,4444
            enable: on
            options:
              kickolduser: true
              telnet-brk-on-sync: true
            connector: serialdev,/dev/optolink,4800e82,local
        dest: /etc/ser2net.yaml
      register: ser2net_config
    - name: Set up optolink device
      copy:
        content: |
          SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="0001", SYMLINK+="optolink", TAG+="systemd"
        dest: /etc/udev/rules.d/99-optolink.rules
      register: optolink_rules
    - name: Reload udev rules
      when: optolink_rules.changed
      shell: udevadm control --reload-rules && udevadm trigger
    - name: Build program
      local_action: command cargo install --bin heating --path . --root target
      become: no
    - name: Install program
      copy:
        src: target/bin/heating
        dest: /usr/local/bin/heating
        mode: 0755
    - name: Enable systemd-networkd-wait-online service
      systemd:
        name: systemd-networkd-wait-online
        enabled: yes
    - name: Install service
      copy:
        content: |
          [Unit]
          Description=heating
          After=network-online.target
          Wants=network-online.target
          BindsTo=dev-optolink.device
          After=dev-optolink.device

          [Service]
          Type=simple
          Environment=RUST_LOG=info
          ExecStart=/usr/local/bin/heating
          Restart=always
          RestartSec=1

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/heating.service
    - name: Enable service
      systemd:
        name: heating
        enabled: yes
        state: restarted
