#!/bin/bash

set -e
set -o pipefail
set -o nounset

ip="${1}"

./cargo-pi build --release &&
rsync -avz ./ pi@"${ip}":reservoir/ --exclude target/debug --exclude target/release &&
ssh pi@"${ip}" -t 'bash -l -c "stty isig intr ^C -echoctl && cd reservoir && sudo ./target/arm-unknown-linux-gnueabihf/release/storage-tank"'
