[package]
name = "hc-sr04"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
ordered-float = "1.0"
rppal = { version = "0.10.0", git = "https://github.com/golemparts/rppal", rev = "3932b8eb97e714d2715f3929555a3a0653ea565e" }
