[package]
name = "hc-sr04"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
ordered-float = "1.0"
rppal = { version = "0.10.0", git = "https://github.com/golemparts/rppal", rev = "79ce7af158f5940ab6c2ac9c607b2d7e5c2e5540" }
