#!/usr/bin/env bash

set -euo pipefail

user="${SSH_USER-root}"
host="${SSH_HOST-heating}"
ssh_host="${user}@${host}"
binary_name="$(basename "${1}")"
remote_path="/tmp/${binary_name}"

ssh "${ssh_host}" "rc-service '${binary_name}' stop" || true
ssh "${ssh_host}" "rc-service ser2net start" || true
ssh "${ssh_host}" "kill \$(pgrep '${binary_name}')" || true
rsync -avz "${1}" "${ssh_host}:${remote_path}"
ssh -t "${ssh_host}" "RUST_LOG='${RUST_LOG-}' OPTOLINK_DEVICE='${OPTOLINK_DEVICE-}' ESPHOME_ENCRYPTION_KEY='${ESPHOME_ENCRYPTION_KEY-}' '${remote_path}'"
