on: [pull_request, push]

name: CI

jobs:
  ci:
    uses: reitermarkus/.github/.github/workflows/cargo-build-publish.yml@d0534ac87836cb9fe1cc64022d6e9231810f3503 # main
    secrets:
      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
